# Generated by Django 3.2.5 on 2021-12-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='分类标题')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('search_key', models.CharField(max_length=32, verbose_name='搜索关键字')),
                ('url', models.CharField(max_length=100, verbose_name='网址')),
                ('source', models.CharField(max_length=32, verbose_name='数据来源')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_assistant.category', verbose_name='所属类别')),
            ],
        ),
    ]
