# Generated by Django 3.2.5 on 2021-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(default=None, verbose_name='收藏夹创建时间'),
        ),
        migrations.AddField(
            model_name='info',
            name='create_time',
            field=models.DateTimeField(default=None, verbose_name='信息爬取时间'),
        ),
    ]
